name: Koos Jeremiasse
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48452
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff8f2'
    - '#1a0a17'
    - '#4b3c3f'
    - '#a6c9d0'
    - '#878575'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
