name: Koos Jeremiasse
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48452
title: Welkom
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#333333'
    - '#1c8fce'
    - '#fefefe'
    - '#999999'
    - '#a6002c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
